# @CineControl.CinemaService.API_HostAddress = http://localhost:5112
@CineControl.CinemaService.API_HostAddress = http://gateway.cinecontrol.local/cinema


POST  {{CineControl.CinemaService.API_HostAddress}}/api/v1/Cinemas
Content-Type: application/json
X-TenantId: 3fa85f64-5717-4562-b3fc-2c963f66afa6

{
  "tenantId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "name": "test",
  "address": "testowa2",
  "city": "test",
  "state": "test",
  "zipCode": "21-902",
  "theaterConfigs": [
    {
      "name": "SuperDuper",
      "seatingCapacity": 20,
      "seatsPerRow": 5
    }
  ]
}
