services:
  cinemaservice:
    build:
      context: .
      dockerfile: src/CineControl.CinemaService.API/Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cinemaservice.rule=Host(`cinemaservice.cinecontrol.local`)"

  identityservice:
    build:
      context: .
      dockerfile: src/CineControl.IdentityService.API/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.identityservice.rule=Host(`identityservice.cinecontrol.local`)"

  seanceservice:
    build:
      context: .
      dockerfile: src/CineControl.SeanceService.API/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seanceservice.rule=Host(`seanceservice.cinecontrol.local`)"

  cinecontrol:
    build:
      context: .
      dockerfile: src/CineControl/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - cinemaservice
      - identityservice
      - seanceservice
      - tenantservice
      - bookingservice
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cinecontrol.rule=Host(`cinecontrol.local`)"

  bookingservice:
    build:
      context: .
      dockerfile: src/CineControl.BookingService.API/Dockerfile
    ports:
      - "8085:8080"
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookingservice.rule=Host(`bookingservice.cinecontrol.local`)"

  tenantservice:
    build:
      context: .
      dockerfile: src/CineControl.TenantService.API/Dockerfile
    ports:
      - "8085:8080"
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tenantservice.rule=Host(`tenantservice.cinecontrol.local`)"

  websitegateway:
    build: 
      context: .
      dockerfile: src/CineControl.WebsiteGateway/Dockerfile
    ports:
      - "8084:8080"
    depends_on:
      - cinecontrol
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`gateway.cinecontrol.local`)"

  db:
    image: postgres:16.3
    # restart: unless-stopped
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_MULTIPLE_DATABASES: CinemaDB,SeanceDB,AuthDB
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      # start_period: 5s

  traefik:
    image: traefik:v3.2
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --entryPoints.web.address=:80
      - --entryPoints.web.asDefault=true
      # - --entryPoints.web.http.redirections.entryPoint.scheme=https
      # - --entryPoints.web.http.redirections.entryPoint.to=:443
      - --entryPoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres-data-prod: