<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Common/CineControl.Common.Clients.IdentityService/CineControl.Common.Clients.IdentityService.csproj" />
    <ProjectReference Include="../Common/CineControl.Common.Clients.TenantService/CineControl.Common.Clients.TenantService.csproj" />
    <ProjectReference Include="../Common/CineControl.Common.JWTProvider/CineControl.Common.JWTProvider.csproj" />
    <ProjectReference Include="../Common/CineControl.Common.ServiceDefaults/CineControl.Common.ServiceDefaults.csproj" />
    <ProjectReference Include="../Common/CineControl.Common/CineControl.Common.csproj" />
  </ItemGroup>

</Project>
