# @CineControl.IdentityService.API_HostAddress = http://localhost:5093
# @CineControl.IdentityService.API_HostAddress = http://identityservice.cinecontrol.local
@CineControl.IdentityService.API_HostAddress = http://gateway.cinecontrol.local/identity

POST {{CineControl.IdentityService.API_HostAddress}}/api/v1/Account/Register
Content-Type: application/json
X-TenantId: 3fa85f64-5717-4562-b3fc-2c963f66afa6

{
    "Username": "Testowy",
    "Email": "Testowy@test.com",
    "Password":"T3st@wy"
}

###

POST {{CineControl.IdentityService.API_HostAddress}}/api/v1/Account/Register
Content-Type: application/json
X-TenantId: 3fa85f64-5717-4562-b3fc-2c963f66afa6

{
    "Username": "Testowy2",
    "Email": "Testowy2@test.com",
    "Password":"T3st@wy",
    "Roles": 1
}

###

POST {{CineControl.IdentityService.API_HostAddress}}/api/v1/Account/Login
Content-Type: application/json
X-TenantId: 3fa85f64-5717-4562-b3fc-2c963f66afa6

{
    "Username": "Testowy2",
    "Password":"T3st@wy"
}

###
# @name Login
POST {{CineControl.IdentityService.API_HostAddress}}/api/v1/Account/Login
Content-Type: application/json
X-TenantId: 3fa85f64-5717-4562-b3fc-2c963f66afa6

{
    "Username": "Testowy",
    "Password":"T3st@wy"
}

###
POST {{CineControl.IdentityService.API_HostAddress}}/api/v1/Account/Login
Content-Type: application/json
X-TenantId: 3fa85f64-5717-4562-b3fc-2c963f66afa6

{
    "Username": "Testowy2",
    "Password":"T3st@wy"
}
###
# @name GetUser
@authToken = {{Login.response.body.accessToken}}
GET {{CineControl.IdentityService.API_HostAddress}}/api/v1/User/GetUser
Authorization: Bearer {{authToken}}

###

PUT {{CineControl.IdentityService.API_HostAddress}}/api/v1/Roles/AddRole
Authorization: Bearer {{authToken}}

Content-Type: application/json

{
    "Username": "{{GetUser.response.body.username}}",
    "Role": "Operator"
}