@CineControl.IdentityService.API_HostAddress = http://localhost:5093
#@CineControl.IdentityService.API_HostAddress = http://identityservice.cinecontrol.local

POST {{CineControl.IdentityService.API_HostAddress}}/api/v1/Auth/Register
Content-Type: application/json

{
    "Username": "Testowy",
    "Email": "Testowy@test.com",
    "Password":"T3st@wy"
}

###
# @name Login
POST {{CineControl.IdentityService.API_HostAddress}}/api/v1/Auth/Login
Content-Type: application/json

{
    "Username": "Testowy",
    "Password":"T3st@wy"
}

###
# @name GetUser
@authToken = {{Login.response.body.accessToken}}
GET {{CineControl.IdentityService.API_HostAddress}}/api/v1/User/GetUser
Authorization: Bearer {{authToken}}

###

PUT {{CineControl.IdentityService.API_HostAddress}}/api/v1/Roles/AddRole
Authorization: Bearer {{authToken}}

Content-Type: application/json

{
    "Username": "{{GetUser.response.body.username}}",
    "Role": "Operator"
}