@CineControl.IdentityService.API_HostAddress = http://localhost:5188
# @CineControl.IdentityService.API_HostAddress = http://identityservice.cinecontrol.local

POST {{CineControl.IdentityService.API_HostAddress}}/api/v1/Tenant
Content-Type: application/json

{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "name": "string",
  "description": "string"
}